"""
Seed data for the AI GRC Control Mapping Assistant.

Controls are organized by THEME (10 common control domains that every
enterprise security program has to cover) and then expressed once per
framework (NIST CSF 2.0, NIST SP 800-53 Rev.5, ISO/IEC 27001:2022,
PCI DSS 4.0, SOC 2 TSC). This is what makes cross-framework mapping
possible: each control carries a `theme` tag plus free-text `keywords`
that the mapping engine matches against.

This is a curated representative sample (~50 controls), not an
exhaustive reproduction of any standard -- enough to demonstrate real
mapping logic and gap/risk analysis end to end.
"""

CONTROL_THEMES = [
    "access_control_mfa",
    "account_lifecycle_management",
    "encryption_data_protection",
    "logging_monitoring",
    "vulnerability_patch_management",
    "incident_response",
    "third_party_vendor_risk",
    "data_classification_handling",
    "security_awareness_training",
    "business_continuity_dr",
]

# Each entry: control_uid, framework, control_id, title, description, category,
# keywords, evidence_requirements, testing_procedures, theme
CONTROLS = [
    # ---------------- 1. Access Control / MFA / Privileged Access ----------------
    dict(control_uid="NISTCSF_PR.AA-05", framework="NIST CSF 2.0", control_id="PR.AA-05",
         title="Identity Management and Access Control",
         description="Identities and credentials are managed, verified, and revoked according to risk, and access is limited to authorized users, processes, and devices.",
         category="Protect", theme="access_control_mfa",
         keywords="mfa,multi-factor authentication,privileged access,access review,identity,credential,least privilege,quarterly review",
         evidence_requirements="Access review logs, MFA enrollment reports, privileged account inventory",
         testing_procedures="Sample privileged accounts and confirm MFA enforcement; review access recertification evidence for the period"),
    dict(control_uid="NIST80053_AC-2", framework="NIST SP 800-53 Rev5", control_id="AC-2",
         title="Account Management",
         description="The organization manages information system accounts, including establishment, activation, modification, review, and removal, with periodic review of privileged accounts.",
         category="Access Control", theme="access_control_mfa",
         keywords="account management,privileged access,access review,quarterly review,provisioning,deprovisioning",
         evidence_requirements="Account creation/termination tickets, periodic access certification reports",
         testing_procedures="Test a sample of new, modified, and terminated accounts against approval records"),
    dict(control_uid="NIST80053_IA-2", framework="NIST SP 800-53 Rev5", control_id="IA-2",
         title="Identification and Authentication (Organizational Users)",
         description="The system uniquely identifies and authenticates organizational users, and implements multi-factor authentication for privileged and non-privileged accounts.",
         category="Identification and Authentication", theme="access_control_mfa",
         keywords="mfa,multi-factor authentication,authentication,privileged access,identification",
         evidence_requirements="MFA configuration standards, authentication logs",
         testing_procedures="Verify MFA is enforced for all privileged and remote access sessions"),
    dict(control_uid="ISO27001_A.5.15", framework="ISO/IEC 27001:2022", control_id="A.5.15",
         title="Access Control",
         description="Rules to control physical and logical access to information and other associated assets are established and implemented based on business and information security requirements.",
         category="Organizational Controls", theme="access_control_mfa",
         keywords="access control,privileged access,mfa,least privilege,access review",
         evidence_requirements="Access control policy, access matrix, review records",
         testing_procedures="Review access control policy and sample enforcement evidence"),
    dict(control_uid="ISO27001_A.8.5", framework="ISO/IEC 27001:2022", control_id="A.8.5",
         title="Secure Authentication",
         description="Secure authentication technologies and procedures are implemented based on information access restrictions and the topic-specific policy on access control.",
         category="Technological Controls", theme="access_control_mfa",
         keywords="mfa,multi-factor authentication,secure authentication,privileged access",
         evidence_requirements="Authentication standard, MFA rollout evidence",
         testing_procedures="Confirm MFA is configured on privileged and remote-access systems"),
    dict(control_uid="PCIDSS_8.4", framework="PCI DSS 4.0", control_id="8.4",
         title="Multi-Factor Authentication",
         description="Multi-factor authentication is implemented to secure access into the cardholder data environment, for all non-console administrative access and all remote access.",
         category="Requirement 8", theme="access_control_mfa",
         keywords="mfa,multi-factor authentication,cardholder data environment,privileged access,remote access",
         evidence_requirements="MFA configuration evidence, CDE access logs",
         testing_procedures="Observe MFA prompts for administrative and remote CDE access"),
    dict(control_uid="PCIDSS_7.2", framework="PCI DSS 4.0", control_id="7.2",
         title="Access Control Model / Need-to-Know",
         description="Access to system components and data is appropriately defined and assigned based on job classification and function, with periodic review of access privileges.",
         category="Requirement 7", theme="access_control_mfa",
         keywords="access review,least privilege,privileged access,quarterly review,need to know",
         evidence_requirements="Access control matrix, quarterly access review sign-off",
         testing_procedures="Sample user access and confirm alignment with documented role-based access model"),
    dict(control_uid="SOC2_CC6.1", framework="SOC 2 TSC", control_id="CC6.1",
         title="Logical Access Security",
         description="The entity implements logical access security software, infrastructure, and architectures to protect information assets, including MFA and periodic access review.",
         category="Common Criteria - Logical Access", theme="access_control_mfa",
         keywords="mfa,multi-factor authentication,logical access,privileged access,access review,quarterly review",
         evidence_requirements="Access provisioning records, MFA policy, quarterly access review",
         testing_procedures="Inspect access provisioning workflow and MFA enforcement configuration"),

    # ---------------- 2. Account Lifecycle Management ----------------
    dict(control_uid="NISTCSF_PR.AA-01", framework="NIST CSF 2.0", control_id="PR.AA-01",
         title="Identity and Credential Issuance, Management, and Revocation",
         description="Identities and credentials for authorized users, services, and hardware are managed by the organization across their lifecycle.",
         category="Protect", theme="account_lifecycle_management",
         keywords="account lifecycle,provisioning,deprovisioning,termination,onboarding,offboarding",
         evidence_requirements="Joiner/mover/leaver process records, termination checklists",
         testing_procedures="Sample terminated employees and confirm timely account deactivation"),
    dict(control_uid="NIST80053_AC-2_1", framework="NIST SP 800-53 Rev5", control_id="AC-2(1)",
         title="Automated System Account Management",
         description="The organization employs automated mechanisms to support account management, including timely disabling of accounts upon termination.",
         category="Access Control", theme="account_lifecycle_management",
         keywords="automated deprovisioning,termination,account lifecycle,offboarding",
         evidence_requirements="HR-to-IT termination feed logs, automated deactivation reports",
         testing_procedures="Verify automated disablement triggers within policy-defined SLA after termination"),
    dict(control_uid="ISO27001_A.5.16", framework="ISO/IEC 27001:2022", control_id="A.5.16",
         title="Identity Management",
         description="The full life cycle of identities is managed, from creation to eventual disabling, in a manner appropriate to the organization's needs.",
         category="Organizational Controls", theme="account_lifecycle_management",
         keywords="identity lifecycle,provisioning,deprovisioning,onboarding,offboarding",
         evidence_requirements="Identity lifecycle procedure, HR/IT integration evidence",
         testing_procedures="Trace a sample of new hires and leavers through the identity lifecycle process"),
    dict(control_uid="PCIDSS_7.3", framework="PCI DSS 4.0", control_id="7.3",
         title="Access Control Systems and Terminated User Removal",
         description="Access to system components is managed via access control systems, with revocation of access immediately upon termination or role change.",
         category="Requirement 7", theme="account_lifecycle_management",
         keywords="termination,account lifecycle,offboarding,role change,deprovisioning",
         evidence_requirements="Termination access revocation logs",
         testing_procedures="Sample terminations and confirm access was revoked within required timeframe"),
    dict(control_uid="SOC2_CC6.2", framework="SOC 2 TSC", control_id="CC6.2",
         title="User Registration and Deregistration",
         description="Prior to issuing system credentials, the entity registers and authorizes new users; access is removed when no longer required, including upon termination.",
         category="Common Criteria - Logical Access", theme="account_lifecycle_management",
         keywords="account lifecycle,termination,offboarding,onboarding,provisioning",
         evidence_requirements="New hire access request forms, termination tickets",
         testing_procedures="Inspect a sample of user registration and deregistration events"),

    # ---------------- 3. Encryption / Data Protection ----------------
    dict(control_uid="NISTCSF_PR.DS-01", framework="NIST CSF 2.0", control_id="PR.DS-01",
         title="Protection of Data-at-Rest",
         description="The confidentiality, integrity, and availability of data-at-rest are protected, typically through encryption.",
         category="Protect", theme="encryption_data_protection",
         keywords="encryption,data at rest,confidentiality,key management",
         evidence_requirements="Encryption standard, key management procedure",
         testing_procedures="Confirm encryption is enabled on databases and storage containing sensitive data"),
    dict(control_uid="NISTCSF_PR.DS-02", framework="NIST CSF 2.0", control_id="PR.DS-02",
         title="Protection of Data-in-Transit",
         description="The confidentiality, integrity, and availability of data-in-transit are protected.",
         category="Protect", theme="encryption_data_protection",
         keywords="encryption,data in transit,tls,confidentiality",
         evidence_requirements="Network encryption standard, TLS configuration scans",
         testing_procedures="Verify TLS 1.2+ enforced on external-facing services carrying sensitive data"),
    dict(control_uid="NIST80053_SC-28", framework="NIST SP 800-53 Rev5", control_id="SC-28",
         title="Protection of Information at Rest",
         description="The system protects the confidentiality and integrity of information at rest using cryptographic mechanisms.",
         category="System and Communications Protection", theme="encryption_data_protection",
         keywords="encryption,data at rest,cryptography,key management",
         evidence_requirements="Cryptographic module inventory, encryption scan results",
         testing_procedures="Sample storage volumes and confirm cryptographic protection is enabled"),
    dict(control_uid="ISO27001_A.8.24", framework="ISO/IEC 27001:2022", control_id="A.8.24",
         title="Use of Cryptography",
         description="Rules for the effective use of cryptography, including cryptographic key management, are defined and implemented.",
         category="Technological Controls", theme="encryption_data_protection",
         keywords="encryption,cryptography,key management,data protection",
         evidence_requirements="Cryptography policy, key management procedure",
         testing_procedures="Review cryptographic standards and sample implementation evidence"),
    dict(control_uid="PCIDSS_3.5", framework="PCI DSS 4.0", control_id="3.5",
         title="Protection of Stored Account Data",
         description="Primary account data is rendered unreadable anywhere it is stored, via strong cryptography and associated key management processes.",
         category="Requirement 3", theme="encryption_data_protection",
         keywords="encryption,data at rest,cardholder data,key management",
         evidence_requirements="Encryption architecture diagram, key management procedures",
         testing_procedures="Inspect storage locations for cardholder data and confirm rendering methods"),
    dict(control_uid="PCIDSS_4.2", framework="PCI DSS 4.0", control_id="4.2",
         title="Protection of Cardholder Data with Strong Cryptography During Transmission",
         description="PAN is protected with strong cryptography during transmission over open, public networks.",
         category="Requirement 4", theme="encryption_data_protection",
         keywords="encryption,data in transit,tls,cardholder data",
         evidence_requirements="Network diagrams, TLS certificates, transmission encryption configuration",
         testing_procedures="Verify strong cryptography protects PAN transmission across all identified channels"),
    dict(control_uid="SOC2_CC6.7", framework="SOC 2 TSC", control_id="CC6.7",
         title="Transmission and Movement of Data",
         description="The entity restricts the transmission, movement, and removal of information to authorized users and protects it during transmission, storage, and disposal.",
         category="Common Criteria - Logical Access", theme="encryption_data_protection",
         keywords="encryption,data in transit,data at rest,data protection",
         evidence_requirements="Data transmission policy, encryption configuration evidence",
         testing_procedures="Inspect encryption configuration for data transmission and storage"),

    # ---------------- 4. Logging & Monitoring ----------------
    dict(control_uid="NISTCSF_DE.CM-01", framework="NIST CSF 2.0", control_id="DE.CM-01",
         title="Continuous Monitoring",
         description="Networks and network services are monitored to find potentially adverse events.",
         category="Detect", theme="logging_monitoring",
         keywords="logging,monitoring,siem,continuous monitoring,alerting",
         evidence_requirements="SIEM alert configuration, monitoring coverage matrix",
         testing_procedures="Confirm critical systems are onboarded to centralized logging and monitoring"),
    dict(control_uid="NIST80053_AU-6", framework="NIST SP 800-53 Rev5", control_id="AU-6",
         title="Audit Record Review, Analysis, and Reporting",
         description="The organization reviews and analyzes audit records for indications of inappropriate or unusual activity and reports findings.",
         category="Audit and Accountability", theme="logging_monitoring",
         keywords="logging,log review,monitoring,audit records,siem",
         evidence_requirements="Log review procedures, sample audit reports",
         testing_procedures="Sample log review activity and confirm findings were investigated"),
    dict(control_uid="ISO27001_A.8.15", framework="ISO/IEC 27001:2022", control_id="A.8.15",
         title="Logging",
         description="Logs that record activities, exceptions, faults, and other relevant events are produced, stored, protected, and analyzed.",
         category="Technological Controls", theme="logging_monitoring",
         keywords="logging,log management,monitoring,audit trail",
         evidence_requirements="Logging standard, log retention configuration",
         testing_procedures="Confirm logging is enabled and retained per policy on in-scope systems"),
    dict(control_uid="PCIDSS_10.2", framework="PCI DSS 4.0", control_id="10.2",
         title="Audit Logs to Support Detection of Anomalies",
         description="Audit logs are implemented to support the detection of anomalies and suspicious activity, and forensic analysis.",
         category="Requirement 10", theme="logging_monitoring",
         keywords="logging,audit logs,monitoring,siem,forensics",
         evidence_requirements="Audit log configuration, log retention evidence",
         testing_procedures="Verify audit logging is enabled for all in-scope system components"),
    dict(control_uid="SOC2_CC7.2", framework="SOC 2 TSC", control_id="CC7.2",
         title="System Monitoring",
         description="The entity monitors system components and the operation of controls to detect anomalies indicative of malicious acts, errors, or events.",
         category="Common Criteria - System Operations", theme="logging_monitoring",
         keywords="monitoring,logging,siem,anomaly detection,alerting",
         evidence_requirements="Monitoring tool configuration, alert escalation procedures",
         testing_procedures="Inspect monitoring tool coverage and sample alert-to-resolution tickets"),

    # ---------------- 5. Vulnerability / Patch Management ----------------
    dict(control_uid="NISTCSF_ID.RA-01", framework="NIST CSF 2.0", control_id="ID.RA-01",
         title="Vulnerability Identification",
         description="Vulnerabilities in assets are identified, validated, and recorded.",
         category="Identify", theme="vulnerability_patch_management",
         keywords="vulnerability management,vulnerability scanning,patching",
         evidence_requirements="Vulnerability scan reports, vulnerability register",
         testing_procedures="Confirm regular vulnerability scans are performed and results tracked"),
    dict(control_uid="NIST80053_RA-5", framework="NIST SP 800-53 Rev5", control_id="RA-5",
         title="Vulnerability Monitoring and Scanning",
         description="The organization monitors and scans for vulnerabilities in the system and remediates legitimate findings in accordance with risk assessment.",
         category="Risk Assessment", theme="vulnerability_patch_management",
         keywords="vulnerability management,vulnerability scanning,patch management,remediation",
         evidence_requirements="Scan schedules, remediation SLAs, ticket closure evidence",
         testing_procedures="Sample vulnerability findings and confirm remediation within SLA"),
    dict(control_uid="ISO27001_A.8.8", framework="ISO/IEC 27001:2022", control_id="A.8.8",
         title="Management of Technical Vulnerabilities",
         description="Information about technical vulnerabilities is obtained, exposure evaluated, and appropriate measures taken to address risk.",
         category="Technological Controls", theme="vulnerability_patch_management",
         keywords="vulnerability management,patch management,vulnerability scanning",
         evidence_requirements="Vulnerability management procedure, patch compliance reports",
         testing_procedures="Review vulnerability handling process and sample patch deployment evidence"),
    dict(control_uid="PCIDSS_11.3", framework="PCI DSS 4.0", control_id="11.3",
         title="External and Internal Vulnerability Scans",
         description="External and internal vulnerability scans are performed regularly and after significant changes, with high-risk vulnerabilities resolved.",
         category="Requirement 11", theme="vulnerability_patch_management",
         keywords="vulnerability scanning,vulnerability management,remediation",
         evidence_requirements="Quarterly scan reports (ASV for external), remediation evidence",
         testing_procedures="Inspect scan reports and confirm high-risk findings were remediated and rescanned"),
    dict(control_uid="SOC2_CC7.1", framework="SOC 2 TSC", control_id="CC7.1",
         title="Vulnerability Detection",
         description="The entity uses detection and monitoring procedures to identify vulnerabilities and configuration changes that introduce risk.",
         category="Common Criteria - System Operations", theme="vulnerability_patch_management",
         keywords="vulnerability management,vulnerability scanning,configuration monitoring",
         evidence_requirements="Vulnerability scanning tool output, patch management records",
         testing_procedures="Confirm vulnerability scans are performed on a defined cadence with tracked remediation"),

    # ---------------- 6. Incident Response ----------------
    dict(control_uid="NISTCSF_RS.MA-01", framework="NIST CSF 2.0", control_id="RS.MA-01",
         title="Incident Response Execution",
         description="The incident response plan is executed once an incident is declared, in coordination with relevant third parties.",
         category="Respond", theme="incident_response",
         keywords="incident response,ir plan,breach,security incident",
         evidence_requirements="Incident response plan, incident tickets, tabletop exercise results",
         testing_procedures="Review a sample incident from detection through closure against the IR plan"),
    dict(control_uid="NIST80053_IR-4", framework="NIST SP 800-53 Rev5", control_id="IR-4",
         title="Incident Handling",
         description="The organization implements an incident handling capability including preparation, detection, analysis, containment, and recovery.",
         category="Incident Response", theme="incident_response",
         keywords="incident response,containment,recovery,security incident",
         evidence_requirements="Incident handling procedure, incident tracking log",
         testing_procedures="Sample incident tickets and confirm handling phases were followed"),
    dict(control_uid="ISO27001_A.5.24", framework="ISO/IEC 27001:2022", control_id="A.5.24",
         title="Information Security Incident Management Planning",
         description="The organization plans and prepares for managing information security incidents by defining roles, responsibilities, and processes.",
         category="Organizational Controls", theme="incident_response",
         keywords="incident response,incident management,security incident",
         evidence_requirements="Incident management plan, roles and responsibilities matrix",
         testing_procedures="Review incident management plan and evidence of team readiness (e.g., tabletop exercises)"),
    dict(control_uid="PCIDSS_12.10", framework="PCI DSS 4.0", control_id="12.10",
         title="Incident Response Plan",
         description="An incident response plan exists and is ready to be activated in the event of a suspected or confirmed security incident.",
         category="Requirement 12", theme="incident_response",
         keywords="incident response,ir plan,breach,security incident",
         evidence_requirements="Documented IR plan, annual test results",
         testing_procedures="Confirm IR plan is tested at least annually and roles are assigned"),
    dict(control_uid="SOC2_CC7.3", framework="SOC 2 TSC", control_id="CC7.3",
         title="Incident Evaluation and Response",
         description="The entity evaluates security events to determine whether they could or did result in a failure to meet objectives, and responds accordingly.",
         category="Common Criteria - System Operations", theme="incident_response",
         keywords="incident response,security incident,containment",
         evidence_requirements="Incident evaluation records, response documentation",
         testing_procedures="Sample security events and trace evaluation and response actions taken"),

    # ---------------- 7. Third-Party / Vendor Risk ----------------
    dict(control_uid="NISTCSF_GV.SC-01", framework="NIST CSF 2.0", control_id="GV.SC-01",
         title="Cybersecurity Supply Chain Risk Management Program",
         description="A cybersecurity supply chain risk management program, strategy, and objectives are established and agreed to by stakeholders.",
         category="Govern", theme="third_party_vendor_risk",
         keywords="third party risk,vendor risk,supply chain,vendor questionnaire",
         evidence_requirements="Third-party risk management program documentation",
         testing_procedures="Review third-party risk program and confirm stakeholder approval"),
    dict(control_uid="NIST80053_SR-2", framework="NIST SP 800-53 Rev5", control_id="SR-2",
         title="Supply Chain Risk Management Plan",
         description="The organization develops a plan for managing supply chain risk associated with the research, development, and operation of systems.",
         category="Supply Chain Risk Management", theme="third_party_vendor_risk",
         keywords="third party risk,vendor risk,supply chain",
         evidence_requirements="Supply chain risk management plan",
         testing_procedures="Confirm the plan addresses critical suppliers and is reviewed periodically"),
    dict(control_uid="ISO27001_A.5.19", framework="ISO/IEC 27001:2022", control_id="A.5.19",
         title="Information Security in Supplier Relationships",
         description="Processes and procedures are defined and implemented to manage information security risks associated with supplier use.",
         category="Organizational Controls", theme="third_party_vendor_risk",
         keywords="third party risk,vendor risk,supplier,vendor questionnaire",
         evidence_requirements="Supplier security policy, vendor due diligence records",
         testing_procedures="Sample vendor onboarding files and confirm due diligence was performed"),
    dict(control_uid="PCIDSS_12.8", framework="PCI DSS 4.0", control_id="12.8",
         title="Risk to Information Assets from Third-Party Service Provider Relationships",
         description="Policies and procedures are maintained to manage service providers with whom account data is shared or that could affect security.",
         category="Requirement 12", theme="third_party_vendor_risk",
         keywords="third party risk,vendor risk,service provider,vendor questionnaire",
         evidence_requirements="Service provider inventory, due diligence and monitoring records",
         testing_procedures="Confirm service provider list is maintained and due diligence/monitoring is performed"),
    dict(control_uid="SOC2_CC9.2", framework="SOC 2 TSC", control_id="CC9.2",
         title="Vendor and Business Partner Risk Management",
         description="The entity assesses and manages risks associated with vendors and business partners.",
         category="Common Criteria - Risk Mitigation", theme="third_party_vendor_risk",
         keywords="third party risk,vendor risk,vendor questionnaire,business partner",
         evidence_requirements="Vendor risk assessments, vendor questionnaires",
         testing_procedures="Sample critical vendors and confirm risk assessments were completed and reviewed"),

    # ---------------- 8. Data Classification & Handling ----------------
    dict(control_uid="NISTCSF_PR.DS-11", framework="NIST CSF 2.0", control_id="PR.DS-11",
         title="Data Classification",
         description="Data is classified and handled according to sensitivity and criticality to support consistent protection.",
         category="Protect", theme="data_classification_handling",
         keywords="data classification,data handling,sensitivity,data governance",
         evidence_requirements="Data classification policy, data inventory",
         testing_procedures="Sample data repositories and confirm classification labels are applied"),
    dict(control_uid="NIST80053_MP-2", framework="NIST SP 800-53 Rev5", control_id="MP-2",
         title="Media Access",
         description="The organization restricts access to digital and non-digital media containing sensitive information to authorized individuals.",
         category="Media Protection", theme="data_classification_handling",
         keywords="data handling,data classification,media protection,sensitive data",
         evidence_requirements="Media handling procedure, access restriction evidence",
         testing_procedures="Confirm access to media containing sensitive data is restricted and logged"),
    dict(control_uid="ISO27001_A.5.12", framework="ISO/IEC 27001:2022", control_id="A.5.12",
         title="Classification of Information",
         description="Information is classified according to information security needs based on confidentiality, integrity, availability, and relevant requirements.",
         category="Organizational Controls", theme="data_classification_handling",
         keywords="data classification,information classification,sensitivity",
         evidence_requirements="Classification policy, labeling standard",
         testing_procedures="Review classification scheme and sample labeled assets"),
    dict(control_uid="PCIDSS_9.4", framework="PCI DSS 4.0", control_id="9.4",
         title="Media with Cardholder Data is Secured",
         description="Media containing cardholder data is classified, securely stored, and destroyed when no longer needed for business or legal reasons.",
         category="Requirement 9", theme="data_classification_handling",
         keywords="data classification,data handling,media protection,cardholder data,retention",
         evidence_requirements="Media inventory, destruction certificates",
         testing_procedures="Sample media storage and destruction records for cardholder data"),
    dict(control_uid="SOC2_CC6.5", framework="SOC 2 TSC", control_id="CC6.5",
         title="Data Classification and Handling",
         description="The entity identifies and classifies data and implements controls to protect it based on classification throughout its lifecycle.",
         category="Common Criteria - Logical Access", theme="data_classification_handling",
         keywords="data classification,data handling,data governance,sensitivity",
         evidence_requirements="Data classification policy, handling procedures",
         testing_procedures="Sample data assets and confirm classification-appropriate handling controls"),

    # ---------------- 9. Security Awareness Training ----------------
    dict(control_uid="NISTCSF_PR.AT-01", framework="NIST CSF 2.0", control_id="PR.AT-01",
         title="Security Awareness Training",
         description="Personnel are provided with security awareness education and training so they can perform their cybersecurity-related duties and responsibilities.",
         category="Protect", theme="security_awareness_training",
         keywords="security awareness,training,phishing,education",
         evidence_requirements="Training completion records, phishing simulation results",
         testing_procedures="Sample employees and confirm annual training completion"),
    dict(control_uid="NIST80053_AT-2", framework="NIST SP 800-53 Rev5", control_id="AT-2",
         title="Literacy Training and Awareness",
         description="The organization provides security literacy training to system users, including recognizing and reporting potential indicators of insider threat.",
         category="Awareness and Training", theme="security_awareness_training",
         keywords="security awareness,training,insider threat,education",
         evidence_requirements="Training curriculum, completion tracking",
         testing_procedures="Confirm training is assigned at onboarding and annually thereafter"),
    dict(control_uid="ISO27001_A.6.3", framework="ISO/IEC 27001:2022", control_id="A.6.3",
         title="Information Security Awareness, Education and Training",
         description="Personnel receive appropriate awareness education and training and regular updates on organizational information security policy.",
         category="People Controls", theme="security_awareness_training",
         keywords="security awareness,training,education",
         evidence_requirements="Training program documentation, attendance/completion records",
         testing_procedures="Sample personnel records and confirm training completion evidence"),
    dict(control_uid="PCIDSS_12.6", framework="PCI DSS 4.0", control_id="12.6",
         title="Security Awareness Program",
         description="A formal security awareness program is implemented to make personnel aware of the entity's information security policy and their responsibilities.",
         category="Requirement 12", theme="security_awareness_training",
         keywords="security awareness,training,phishing",
         evidence_requirements="Awareness program materials, completion records",
         testing_procedures="Confirm awareness training is delivered upon hire and at least annually"),
    dict(control_uid="SOC2_CC1.4", framework="SOC 2 TSC", control_id="CC1.4",
         title="Commitment to Competence",
         description="The entity demonstrates a commitment to attract, develop, and retain competent individuals, including through security training.",
         category="Common Criteria - Control Environment", theme="security_awareness_training",
         keywords="security awareness,training,competence,education",
         evidence_requirements="Training records, competency assessments",
         testing_procedures="Sample personnel files and confirm role-appropriate training was completed"),

    # ---------------- 10. Business Continuity / Disaster Recovery ----------------
    dict(control_uid="NISTCSF_RC.RP-01", framework="NIST CSF 2.0", control_id="RC.RP-01",
         title="Recovery Plan Execution",
         description="The recovery portion of the incident response plan is executed once initiated from the incident response process.",
         category="Recover", theme="business_continuity_dr",
         keywords="business continuity,disaster recovery,recovery plan,resilience",
         evidence_requirements="Business continuity/DR plan, recovery test results",
         testing_procedures="Review most recent DR test and confirm recovery objectives were met"),
    dict(control_uid="NIST80053_CP-2", framework="NIST SP 800-53 Rev5", control_id="CP-2",
         title="Contingency Plan",
         description="The organization develops and maintains a contingency plan for the information system that addresses roles, responsibilities, and recovery procedures.",
         category="Contingency Planning", theme="business_continuity_dr",
         keywords="business continuity,disaster recovery,contingency plan,resilience",
         evidence_requirements="Contingency plan document, annual test results",
         testing_procedures="Confirm contingency plan is tested at least annually and updated based on results"),
    dict(control_uid="ISO27001_A.5.29", framework="ISO/IEC 27001:2022", control_id="A.5.29",
         title="Information Security During Disruption",
         description="The organization plans how to maintain information security at an appropriate level during disruption.",
         category="Organizational Controls", theme="business_continuity_dr",
         keywords="business continuity,disaster recovery,disruption,resilience",
         evidence_requirements="Business continuity plan, disruption response procedures",
         testing_procedures="Review continuity plan and confirm testing evidence"),
    dict(control_uid="PCIDSS_A3.2", framework="PCI DSS 4.0", control_id="A3.2",
         title="Business Continuity Planning",
         description="Designated entities maintain business continuity plans to ensure incident response and forensic readiness capabilities are preserved.",
         category="Appendix A3", theme="business_continuity_dr",
         keywords="business continuity,disaster recovery,resilience",
         evidence_requirements="BC/DR plan, test results",
         testing_procedures="Confirm BC/DR plan exists and has been tested within the required period"),
    dict(control_uid="SOC2_A1.3", framework="SOC 2 TSC", control_id="A1.3",
         title="Recovery Plan Testing",
         description="The entity tests recovery plan procedures supporting system recovery to meet its objectives.",
         category="Additional Criteria - Availability", theme="business_continuity_dr",
         keywords="business continuity,disaster recovery,recovery plan,resilience",
         evidence_requirements="DR test plans and results, recovery time objectives",
         testing_procedures="Review most recent recovery test and compare results to defined RTO/RPO"),
]

# ============================================================================
# EXTENDED COVERAGE: threat taxonomies, attack technique frameworks, and
# AI-specific legal/regulatory requirements.
#
# These are NOT all "controls" in the traditional sense -- OWASP and MITRE
# publish threats/attack techniques, not controls. They are modeled here with
# entry_type = 'threat' | 'attack_technique' so the UI and reports can label
# them correctly, while still using the same `theme` tagging so the mapping
# engine and relationship-builder can connect a threat/technique to the
# traditional controls (above) that mitigate it. Where a theme already exists
# above (e.g. access_control_mfa, encryption_data_protection), it is reused
# deliberately to create a real crosswalk from "here's the risk" to "here's
# the control that addresses it."
# ============================================================================

EXTENDED_ENTRIES = [
    # ---------------- OWASP LLM Top 10 (2025) ----------------
    dict(control_uid="OWASP_LLM01", framework="OWASP LLM Top 10", control_id="LLM01",
         title="Prompt Injection", entry_type="threat",
         description="Attacker input manipulates an LLM's behavior or output via crafted prompts, direct or indirect (e.g. via retrieved documents), bypassing intended instructions.",
         category="LLM Application Security", theme="llm_prompt_injection",
         keywords="prompt injection,llm,jailbreak,indirect prompt injection,input validation",
         evidence_requirements="Input/output filtering configuration, red-team test results",
         testing_procedures="Attempt direct and indirect prompt injection payloads against the application in a test environment"),
    dict(control_uid="OWASP_LLM02", framework="OWASP LLM Top 10", control_id="LLM02",
         title="Sensitive Information Disclosure", entry_type="threat",
         description="The LLM may reveal sensitive data (PII, proprietary information, training data artifacts) through its responses.",
         category="LLM Application Security", theme="data_classification_handling",
         keywords="data leakage,sensitive information,llm,pii disclosure,training data",
         evidence_requirements="Output filtering rules, data handling policy for model I/O",
         testing_procedures="Test the model with probing prompts designed to elicit sensitive data and confirm filtering"),
    dict(control_uid="OWASP_LLM03", framework="OWASP LLM Top 10", control_id="LLM03",
         title="Supply Chain Vulnerabilities", entry_type="threat",
         description="Vulnerabilities in third-party models, training data, plugins, or fine-tuning pipelines can compromise the application.",
         category="LLM Application Security", theme="third_party_vendor_risk",
         keywords="supply chain,third party risk,model provenance,vendor risk,llm",
         evidence_requirements="Model/vendor due diligence records, SBOM for AI components",
         testing_procedures="Review provenance and integrity verification for third-party models and datasets"),
    dict(control_uid="OWASP_LLM04", framework="OWASP LLM Top 10", control_id="LLM04",
         title="Data and Model Poisoning", entry_type="threat",
         description="Training, fine-tuning, or embedding data is manipulated to introduce vulnerabilities, backdoors, or bias into the model.",
         category="LLM Application Security", theme="ai_model_integrity",
         keywords="data poisoning,model poisoning,training data integrity,backdoor",
         evidence_requirements="Training data provenance and validation records",
         testing_procedures="Review data ingestion pipeline controls and sample training data validation checks"),
    dict(control_uid="OWASP_LLM06", framework="OWASP LLM Top 10", control_id="LLM06",
         title="Excessive Agency", entry_type="threat",
         description="An LLM-based system is granted excessive functionality, permissions, or autonomy, enabling damaging actions from unexpected outputs.",
         category="LLM Application Security", theme="llm_excessive_agency",
         keywords="excessive agency,llm autonomy,least privilege,human oversight,agent permissions",
         evidence_requirements="Agent permission scoping documentation, human-approval gate configuration",
         testing_procedures="Review the permission scope granted to LLM agents/plugins and confirm least-privilege design"),
    dict(control_uid="OWASP_LLM07", framework="OWASP LLM Top 10", control_id="LLM07",
         title="System Prompt Leakage", entry_type="threat",
         description="System prompts containing sensitive instructions, credentials, or business logic may be disclosed to end users.",
         category="LLM Application Security", theme="llm_prompt_injection",
         keywords="system prompt leakage,prompt disclosure,llm,jailbreak",
         evidence_requirements="System prompt design standard (no secrets in prompts)",
         testing_procedures="Attempt to extract the system prompt via adversarial user input"),
    dict(control_uid="OWASP_LLM10", framework="OWASP LLM Top 10", control_id="LLM10",
         title="Unbounded Consumption", entry_type="threat",
         description="Uncontrolled resource consumption (compute, API calls, cost) from excessive or automated LLM requests, leading to denial of service or financial loss.",
         category="LLM Application Security", theme="api_resource_management",
         keywords="resource consumption,denial of service,rate limiting,llm,cost control",
         evidence_requirements="Rate limiting configuration, usage quota alerts",
         testing_procedures="Confirm rate limiting and quota controls are enforced on LLM API endpoints"),

    # ---------------- MITRE ATLAS (Adversarial Threat Landscape for AI Systems) ----------------
    dict(control_uid="ATLAS_AML.T0043", framework="MITRE ATLAS", control_id="AML.T0043",
         title="Craft Adversarial Data", entry_type="attack_technique",
         description="Adversaries craft data samples designed to cause an ML model to produce incorrect outputs (evasion attacks).",
         category="ML Attack Staging", theme="ai_model_integrity",
         keywords="adversarial examples,evasion attack,model robustness,craft adversarial data",
         evidence_requirements="Adversarial robustness test results",
         testing_procedures="Run adversarial example generation tools against the model and measure misclassification rate"),
    dict(control_uid="ATLAS_AML.T0020", framework="MITRE ATLAS", control_id="AML.T0020",
         title="Poison Training Data", entry_type="attack_technique",
         description="Adversaries manipulate training data to compromise model integrity, introducing backdoors or degrading performance.",
         category="Resource Development", theme="ai_model_integrity",
         keywords="data poisoning,training data integrity,backdoor,model poisoning",
         evidence_requirements="Training data source validation and integrity checks",
         testing_procedures="Review controls preventing unauthorized modification of training datasets"),
    dict(control_uid="ATLAS_AML.T0024", framework="MITRE ATLAS", control_id="AML.T0024",
         title="Exfiltration via ML Inference API", entry_type="attack_technique",
         description="Adversaries query a model's inference API repeatedly to reconstruct training data or extract model internals (model extraction/inversion).",
         category="Exfiltration", theme="logging_monitoring",
         keywords="model extraction,model inversion,inference api,data exfiltration,rate limiting",
         evidence_requirements="Inference API rate limiting and anomaly detection logs",
         testing_procedures="Monitor for abnormal query volume/patterns against the inference API and confirm alerting"),
    dict(control_uid="ATLAS_AML.T0018", framework="MITRE ATLAS", control_id="AML.T0018",
         title="Backdoor ML Model", entry_type="attack_technique",
         description="Adversaries introduce a backdoor into a model so it behaves normally except when triggered by a specific input pattern.",
         category="Persistence", theme="ai_model_integrity",
         keywords="backdoor,model integrity,trojan model,persistence",
         evidence_requirements="Model integrity verification / hash validation records",
         testing_procedures="Perform backdoor detection scanning on models sourced from third parties prior to deployment"),
    dict(control_uid="ATLAS_AML.T0040", framework="MITRE ATLAS", control_id="AML.T0040",
         title="ML Model Inference API Access", entry_type="attack_technique",
         description="Adversaries gain unauthorized access to a model's inference API as a foothold for further attacks.",
         category="Initial Access", theme="access_control_mfa",
         keywords="inference api,unauthorized access,mfa,api access control",
         evidence_requirements="API authentication and authorization configuration",
         testing_procedures="Confirm inference API endpoints require authenticated, authorized access"),

    # ---------------- MITRE ATT&CK (Enterprise, representative subset) ----------------
    dict(control_uid="ATTACK_T1078", framework="MITRE ATT&CK", control_id="T1078",
         title="Valid Accounts", entry_type="attack_technique",
         description="Adversaries obtain and abuse credentials of existing accounts to gain initial access, persistence, or evade detection.",
         category="Initial Access / Persistence", theme="access_control_mfa",
         keywords="valid accounts,credential abuse,mfa,privileged access,account compromise",
         evidence_requirements="MFA enforcement logs, anomalous login detection",
         testing_procedures="Confirm MFA is enforced and anomalous account use is monitored and alerted"),
    dict(control_uid="ATTACK_T1110", framework="MITRE ATT&CK", control_id="T1110",
         title="Brute Force", entry_type="attack_technique",
         description="Adversaries attempt to guess or systematically submit credentials to gain unauthorized access.",
         category="Credential Access", theme="access_control_mfa",
         keywords="brute force,credential access,mfa,account lockout,password attack",
         evidence_requirements="Account lockout policy, authentication failure logs",
         testing_procedures="Confirm account lockout and MFA controls mitigate brute-force attempts"),
    dict(control_uid="ATTACK_T1068", framework="MITRE ATT&CK", control_id="T1068",
         title="Exploitation for Privilege Escalation", entry_type="attack_technique",
         description="Adversaries exploit software vulnerabilities to elevate privileges beyond their current access level.",
         category="Privilege Escalation", theme="vulnerability_patch_management",
         keywords="privilege escalation,vulnerability exploitation,patch management",
         evidence_requirements="Vulnerability scan and patch compliance records",
         testing_procedures="Confirm known privilege-escalation vulnerabilities are patched within SLA"),
    dict(control_uid="ATTACK_T1136", framework="MITRE ATT&CK", control_id="T1136",
         title="Create Account", entry_type="attack_technique",
         description="Adversaries create new accounts to maintain persistent access to a compromised environment.",
         category="Persistence", theme="account_lifecycle_management",
         keywords="account creation,persistence,unauthorized account,account lifecycle",
         evidence_requirements="Account creation audit logs, approval workflow records",
         testing_procedures="Sample newly created accounts and confirm each maps to an approved onboarding request"),
    dict(control_uid="ATTACK_T1041", framework="MITRE ATT&CK", control_id="T1041",
         title="Exfiltration Over C2 Channel", entry_type="attack_technique",
         description="Adversaries steal data by exfiltrating it over an existing command-and-control channel.",
         category="Exfiltration", theme="logging_monitoring",
         keywords="data exfiltration,command and control,monitoring,dlp",
         evidence_requirements="Network monitoring and DLP alert logs",
         testing_procedures="Confirm outbound traffic monitoring and DLP controls are in place and alerting"),
    dict(control_uid="ATTACK_T1070", framework="MITRE ATT&CK", control_id="T1070",
         title="Indicator Removal", entry_type="attack_technique",
         description="Adversaries delete or modify logs and other artifacts to hide evidence of their activity.",
         category="Defense Evasion", theme="logging_monitoring",
         keywords="log tampering,indicator removal,log integrity,siem",
         evidence_requirements="Log integrity protection (write-once/centralized log forwarding) configuration",
         testing_procedures="Confirm logs are forwarded to a centralized, access-restricted log store in near real time"),

    # ---------------- OWASP API Security Top 10 (2023) ----------------
    dict(control_uid="OWASP_API1", framework="OWASP API Top 10", control_id="API1:2023",
         title="Broken Object Level Authorization", entry_type="threat",
         description="APIs fail to properly validate that a user is authorized to access the specific object/record they are requesting.",
         category="API Security", theme="access_control_mfa",
         keywords="broken object level authorization,bola,access control,api authorization",
         evidence_requirements="API authorization test results, object-level access control design",
         testing_procedures="Attempt to access another user's object/record by manipulating IDs in API requests"),
    dict(control_uid="OWASP_API2", framework="OWASP API Top 10", control_id="API2:2023",
         title="Broken Authentication", entry_type="threat",
         description="API authentication mechanisms are implemented incorrectly, allowing attackers to compromise tokens or exploit implementation flaws.",
         category="API Security", theme="access_control_mfa",
         keywords="broken authentication,api authentication,mfa,token security",
         evidence_requirements="API authentication standard, token expiration/rotation configuration",
         testing_procedures="Review token issuance, expiration, and revocation mechanisms for API authentication"),
    dict(control_uid="OWASP_API4", framework="OWASP API Top 10", control_id="API4:2023",
         title="Unrestricted Resource Consumption", entry_type="threat",
         description="APIs do not properly limit resource consumption (requests, payload size, compute), enabling denial-of-service or cost-based attacks.",
         category="API Security", theme="api_resource_management",
         keywords="resource consumption,rate limiting,denial of service,api quota",
         evidence_requirements="Rate limiting and throttling configuration",
         testing_procedures="Confirm rate limits, payload size limits, and timeouts are enforced on all API endpoints"),
    dict(control_uid="OWASP_API5", framework="OWASP API Top 10", control_id="API5:2023",
         title="Broken Function Level Authorization", entry_type="threat",
         description="APIs fail to properly restrict access to sensitive functions (e.g. admin functions) based on user role.",
         category="API Security", theme="access_control_mfa",
         keywords="broken function level authorization,privilege escalation,api authorization,least privilege",
         evidence_requirements="Role-based API authorization matrix",
         testing_procedures="Attempt to invoke privileged API functions using a lower-privileged account's token"),
    dict(control_uid="OWASP_API7", framework="OWASP API Top 10", control_id="API7:2023",
         title="Server Side Request Forgery", entry_type="threat",
         description="An API fetches a remote resource without validating the user-supplied URL, allowing attackers to reach internal or unintended destinations.",
         category="API Security", theme="web_injection",
         keywords="ssrf,server side request forgery,input validation,web security",
         evidence_requirements="URL/input validation and network segmentation controls",
         testing_procedures="Test API endpoints that fetch remote resources for SSRF via crafted internal-network URLs"),
    dict(control_uid="OWASP_API8", framework="OWASP API Top 10", control_id="API8:2023",
         title="Security Misconfiguration", entry_type="threat",
         description="APIs and supporting infrastructure are deployed with insecure default configurations, unnecessary features enabled, or missing hardening.",
         category="API Security", theme="security_configuration",
         keywords="security misconfiguration,hardening,default configuration,api security",
         evidence_requirements="Configuration hardening standard and baseline scan results",
         testing_procedures="Compare deployed API configuration against the organization's hardening baseline"),

    # ---------------- OWASP Top 10 Web Application Security Risks (2021) ----------------
    dict(control_uid="OWASP_A01", framework="OWASP Web Top 10", control_id="A01:2021",
         title="Broken Access Control", entry_type="threat",
         description="Restrictions on what authenticated users are allowed to do are not properly enforced, allowing access beyond intended permissions.",
         category="Web Application Security", theme="access_control_mfa",
         keywords="broken access control,least privilege,authorization,web security",
         evidence_requirements="Access control test results, authorization matrix",
         testing_procedures="Attempt privilege escalation and forced browsing to restricted URLs/functions"),
    dict(control_uid="OWASP_A02", framework="OWASP Web Top 10", control_id="A02:2021",
         title="Cryptographic Failures", entry_type="threat",
         description="Sensitive data is exposed due to weak or missing encryption in transit or at rest, or use of deprecated cryptographic algorithms.",
         category="Web Application Security", theme="encryption_data_protection",
         keywords="cryptographic failures,encryption,weak cryptography,data exposure",
         evidence_requirements="Cryptographic standard, TLS/cipher configuration scan results",
         testing_procedures="Scan for weak ciphers/protocols and confirm sensitive data is encrypted at rest and in transit"),
    dict(control_uid="OWASP_A03", framework="OWASP Web Top 10", control_id="A03:2021",
         title="Injection", entry_type="threat",
         description="Untrusted data is sent to an interpreter (SQL, OS command, LDAP, etc.) as part of a command or query, allowing execution of unintended commands.",
         category="Web Application Security", theme="web_injection",
         keywords="injection,sql injection,input validation,parameterized queries",
         evidence_requirements="Secure coding standard, static analysis (SAST) scan results",
         testing_procedures="Perform SAST/DAST scanning and manual testing for injection vulnerabilities"),
    dict(control_uid="OWASP_A05", framework="OWASP Web Top 10", control_id="A05:2021",
         title="Security Misconfiguration", entry_type="threat",
         description="Missing security hardening, unnecessary features enabled, default accounts/passwords, or overly verbose error messages.",
         category="Web Application Security", theme="security_configuration",
         keywords="security misconfiguration,hardening,default credentials,web security",
         evidence_requirements="Hardening baseline and configuration scan results",
         testing_procedures="Compare deployed configuration against a hardening baseline (e.g. CIS Benchmarks)"),
    dict(control_uid="OWASP_A06", framework="OWASP Web Top 10", control_id="A06:2021",
         title="Vulnerable and Outdated Components", entry_type="threat",
         description="Use of components (libraries, frameworks) with known vulnerabilities or that are no longer supported/maintained.",
         category="Web Application Security", theme="vulnerability_patch_management",
         keywords="vulnerable components,outdated components,dependency scanning,patch management",
         evidence_requirements="Software composition analysis (SCA) scan results, dependency inventory",
         testing_procedures="Run SCA tooling against the codebase and confirm known-vulnerable components are remediated"),
    dict(control_uid="OWASP_A07", framework="OWASP Web Top 10", control_id="A07:2021",
         title="Identification and Authentication Failures", entry_type="threat",
         description="Weaknesses in authentication and session management allow attackers to compromise passwords, keys, or session tokens.",
         category="Web Application Security", theme="access_control_mfa",
         keywords="authentication failures,session management,mfa,credential stuffing",
         evidence_requirements="Authentication and session management standard",
         testing_procedures="Test for weak password policy enforcement, session fixation, and credential stuffing resilience"),
    dict(control_uid="OWASP_A09", framework="OWASP Web Top 10", control_id="A09:2021",
         title="Security Logging and Monitoring Failures", entry_type="threat",
         description="Insufficient logging, detection, monitoring, and incident response allow attackers to maintain persistence undetected.",
         category="Web Application Security", theme="logging_monitoring",
         keywords="logging failures,monitoring,siem,incident detection",
         evidence_requirements="Logging coverage inventory, alerting configuration",
         testing_procedures="Confirm security-relevant events are logged, centralized, and alerted upon in near real time"),

    # ---------------- EU AI Act (representative articles) ----------------
    dict(control_uid="EUAIACT_ART6", framework="EU AI Act", control_id="Article 6",
         title="Classification Rules for High-Risk AI Systems", entry_type="legal_requirement",
         description="Defines the criteria and conditions under which an AI system is classified as high-risk, triggering the Act's compliance obligations.",
         category="Classification", theme="eu_ai_act_classification",
         keywords="high risk ai,ai classification,eu ai act,risk categorization",
         evidence_requirements="AI system risk classification assessment and rationale",
         testing_procedures="Review documented classification rationale for each AI system against Annex III use-case categories"),
    dict(control_uid="EUAIACT_ART9", framework="EU AI Act", control_id="Article 9",
         title="Risk Management System", entry_type="legal_requirement",
         description="High-risk AI systems must have a continuous, iterative risk management system covering the entire lifecycle.",
         category="Risk Management", theme="ai_governance_program",
         keywords="ai risk management,risk management system,eu ai act,ai lifecycle",
         evidence_requirements="AI risk management plan, lifecycle risk review records",
         testing_procedures="Confirm a documented, iterative AI risk management process exists and is followed for high-risk systems"),
    dict(control_uid="EUAIACT_ART10", framework="EU AI Act", control_id="Article 10",
         title="Data and Data Governance", entry_type="legal_requirement",
         description="Training, validation, and testing data for high-risk AI systems must meet quality criteria, including relevance, representativeness, and bias examination.",
         category="Data Governance", theme="data_classification_handling",
         keywords="data governance,data quality,training data,bias,eu ai act",
         evidence_requirements="Data governance procedure, dataset quality and bias assessment records",
         testing_procedures="Review training/validation dataset documentation for quality and representativeness criteria"),
    dict(control_uid="EUAIACT_ART13", framework="EU AI Act", control_id="Article 13",
         title="Transparency and Provision of Information to Users", entry_type="legal_requirement",
         description="High-risk AI systems must be designed to ensure operation is sufficiently transparent, with instructions for use provided to deployers.",
         category="Transparency", theme="eu_ai_act_transparency",
         keywords="transparency,ai disclosure,instructions for use,eu ai act,explainability",
         evidence_requirements="User-facing documentation / instructions for use, model card",
         testing_procedures="Review instructions for use and confirm they disclose system capabilities and limitations"),
    dict(control_uid="EUAIACT_ART14", framework="EU AI Act", control_id="Article 14",
         title="Human Oversight", entry_type="legal_requirement",
         description="High-risk AI systems must be designed to allow effective human oversight, including the ability to intervene or halt the system.",
         category="Human Oversight", theme="eu_ai_act_human_oversight",
         keywords="human oversight,human in the loop,ai override,accountability,eu ai act",
         evidence_requirements="Human oversight procedure, override/intervention logs",
         testing_procedures="Confirm a human reviewer can intervene in or halt AI system decisions and that this capability is tested"),
    dict(control_uid="EUAIACT_ART15", framework="EU AI Act", control_id="Article 15",
         title="Accuracy, Robustness and Cybersecurity", entry_type="legal_requirement",
         description="High-risk AI systems must achieve an appropriate level of accuracy, robustness, and cybersecurity throughout their lifecycle.",
         category="Robustness & Security", theme="ai_model_integrity",
         keywords="accuracy,robustness,cybersecurity,ai system security,eu ai act",
         evidence_requirements="Accuracy/robustness test results, adversarial testing records",
         testing_procedures="Review accuracy and adversarial robustness test results against defined acceptance thresholds"),
]

CONTROLS = CONTROLS + EXTENDED_ENTRIES

# Cross-framework relationships are derived automatically at load time
# (any two controls sharing a theme are related) -- see database/db.py:build_relationships()
